export const mapProfileToExcelRow = (s) => ({
  'YEAR': s.YEAR || '',
  'SPONSOR': s.SPONSOR || '',
  'PROJECT NAME': s['PROJECT NAME'] || '',
  'CENTRE CODE': s['CENTRE CODE'] || '',
  'Roll Number': s.ROLL_KEY || '',
  'Registration No. (SSRP, CBT, CLT)': s['Registration no.'] || '',
  'PEER GROUP (A, B, C, D, ...)': s['PEER GROUP'] || '',
  "STUDENT'S NAME": s["STUDENT'S NAME"] || '',
  'GENDER': s.GENDER || '',
  'CATEGORY': s.CATEGORY || '',
  'Embibe Email Id': s['Embibe Email Id'] || '',
  'Embibe Mobile No.': s['Embibe Mobile No.'] || '',
  'Mobile No.': s['Mobile No.'] || '',
  'DATE OF BIRTH': s['DATE OF BIRTH'] || '',
  'Mode of Selection (SSRP/CBT-01/CBT-02)': s['Mode of Selection'] || '',
  'Written Test Marks (240)': s['Written Test Marks (240)'] || '',
  'Interview Marks (90)': s['Interview Marks (90)'] || '',
  'HO Score in Final Admission List (100)': s['HO Score in Final Admission'] || '',
  "FATHER'S NAME": s["FATHER'S NAME"] || '',
  'FATHER NATURE OF WORK': s['FATHER NATURE OF WORK'] || '',
  "FATHER'S INCOME (ANNUAL)": s["FATHER'S INCOME (ANNUAL)"] || '',
  "MOTHER'S NAME": s["MOTHER'S NAME"] || '',
  'MOTHER NATURE OF WORK': s['MOTHER NATURE OF WORK'] || '',
  "MOTHER'S INCOME (ANNUAL)": s["MOTHER'S INCOME (ANNUAL)"] || '',
  'SINGLE CHILD (YES/NO)': s['SINGLE CHILD (YES/NO)'] || '',
  'Number of Siblings': s['Number of Siblings'] || '',
  'PERMANENT ADDRESS': s['PARMANENT ADDRESS'] || s['PERMANENT ADDRESS'] || '',
  'DISTRICT': s.DISTRICT || '',
  'STATE': s.STATE || '',
  'PINCODE': s.PINCODE || '',
  '10th SCHOOL NAME': s['10th SCHOOL NAME'] || '',
  '10th DISTRICT': s['10th DISTRICT'] || '',
  '10th STATE': s['10th STATE'] || '',
  '10th BOARD': s['10th BOARD'] || '',
  '10th Percentage': s['10th Precentage'] || s['10th Percentage'] || '',
  '12th SCHOOL NAME': s['12th SCHOOL NAME'] || '',
  '12th BOARD': s['12th BOARD'] || '',
  '12th DISTRICT': s['12th DISTRICT'] || '',
  '12th STATE': s['12th STATE'] || '',
  '12th Percentage': s['12th Precentage'] || s['12th Percentage'] || '',
  'JEE MAINS 2024-25 SCORE CARD (IF ATTEMPTED)': s['JEE MAINS SCORE CARD'] || '',
  'JEE MAINS 2024-25 Percentile': s['JEE MAINS 2024-25 Precentille'] || s['JEE MAINS 2024-25 Percentile'] || '',
  'JEE Mains 2024-25 Qualification Status': s['JEE Mains Qualification Status'] || '',
  'JEE Advanced 2024-25 Marks': s['JEE Advanced Marks'] || '',
  'JEE Advanced 2024-25 Qualification Status': s['JEE Advanced Qualification Status'] || '',
  'OMR SHEET': s['OMR SHEET'] || '',
  'ADMIT CARD OF CSRL WRITTEN TEST': s['ADMIT CARD OF CSRL WRITTEN TEST'] || '',
  'VACCINATION REPORT': s['VACCINATION REPORT'] || '',
  'KYS': s['KYS'] || '',
  'INTERVIEW SHEET A': s['INTERVIEW SHEET A'] || '',
  'INTERVIEW SHEET B': s['INTERVIEW SHEET B'] || '',
  'SIGNED TERM & CONDITION': s['SIGNED TERM & CONDITION'] || '',
  'SIGNED PARENTS CONSENT': s['SIGNED PARENTS CONSENT'] || '',
  'MEDICAL CERTIFICATE': s['MEDICAL CERTIFICATE'] || '',
  'MEDICAL HISTORY': s['MEDICAL HISTORY'] || '',
  'INDEMNITY CUM DECLARATION': s['INDEMNITY CUM DECLARATION'] || '',
  'DECLARATION CUM AFFIDAVIT': s['DECLARATION CUM AFFIDAVIT'] || '',
  'INCOME CERTIFICATE (Original)': s['INCOME CERTIFICATE (Original)'] || '',
  'BANK STATEMENT': s['BANK STATEMENT'] || '',
  'CLASS 10TH MARKSHEET': s['CLASS 10TH MARKSHEET'] || '',
  'CLASS 10TH PASSING CERTIFICATE': s['CLASS 10TH PASSING CERTIFICATE'] || '',
  'CLASS 12TH MARKSHEET': s['CLASS 12TH MARKSHEET'] || '',
  'CLASS 12TH PASSING CERTIFICATE': s['CLASS 12TH PASSING CERTIFICATE'] || '',
  'AADHAAR CARD NUMBER': s['AADHAAR CARD NUMBER'] || '',
  'CATEGORY CERTIFICATE': s['CATEGORY CERTIFICATE'] || '',
  'PHYSICAL DISABILITY CERTIFICATE': s['PHYSICAL DISABILITY CERTIFICATE'] || '',
  'DOMICILE CERTIFICATE': s['DOMICILE CERTIFICATE'] || '',
  'Email Id': s['Email Id'] || '',
});
