import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line, Legend } from 'recharts';
import { parseFacultyRows } from '../services/facultyImport';
const API = 'https://csrl-app-backed-1.onrender.com/api/faculty-tests';
async function request(path = '', body) {
  const response = await fetch(API + path, { method: body ? 'POST' : 'GET', headers: { 'Content-Type':'application/json', Authorization: `Bearer ${localStorage.getItem('csrl_token') || ''}` }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Faculty request failed.'); return data;
}
const show = v => v === null || v === undefined ? '—' : Number.isFinite(v) ? Math.round(v * 100) / 100 : v;
export default function FacultyTestDashboard({ isAdmin = false }) {
  const [rows,setRows] = useState([]), [loading,setLoading] = useState(true), [error,setError] = useState('');
  const [year,setYear] = useState('ALL'), [test,setTest] = useState('ALL'), [subject,setSubject] = useState('ALL'), [centre,setCentre] = useState('ALL'), [faculty,setFaculty] = useState('');
  const [importYear,setImportYear] = useState('2026-27'), [preview,setPreview] = useState(null), [busy,setBusy] = useState(false), [notice,setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setRows((await request()).rows || []); } catch(e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { let live = true; request().then(d => { if(live) setRows(d.rows || []); }).catch(e => { if(live) setError(e.message); }).finally(() => { if(live) setLoading(false); }); return () => { live = false; }; }, []);
  const options = key => [...new Set(rows.flatMap(r => key === 'centres' ? r.centres : [r[key]]).filter(Boolean))].sort((a,b) => a.localeCompare(b,undefined,{numeric:true}));
  const filtered = useMemo(() => rows.filter(r => (year === 'ALL' || r.year === year) && (test === 'ALL' || r.test === test) && (subject === 'ALL' || r.subject === subject) && (centre === 'ALL' || r.centres.includes(centre))), [rows,year,test,subject,centre]);
  const appeared = filtered.filter(r => r.status === 'APPEARED' && r.marks !== null);
  const mean = key => { const v = appeared.map(r => r[key]).filter(x => x !== null && x !== undefined); return v.length ? v.reduce((a,b) => a+b,0)/v.length : null; };
  const people = [...new Map(filtered.map(r => [r.email,r.name])).entries()];
  const chosen = people.some(([email]) => email === faculty) ? faculty : (people[0]?.[0] || '');
  const history = rows.filter(r => r.email === chosen && (year === 'ALL' || r.year === year) && (subject === 'ALL' || r.subject === subject)).sort((a,b) => (a.date && b.date ? a.date.localeCompare(b.date) : a.test.localeCompare(b.test,undefined,{numeric:true}))).map(r => ({...r,label:`${r.test} (${r.subject})`,percent:r.maxMarks && r.marks !== null ? r.marks/r.maxMarks*100 : null}));
  const ranking = [...filtered].sort((a,b) => (b.marks ?? -Infinity) - (a.marks ?? -Infinity));
  const canRank = test !== 'ALL' && subject !== 'ALL' && year !== 'ALL';
  const upload = async event => { const file = event.target.files?.[0]; event.target.value = ''; if(!file) return; setError('');setPreview(null);setBusy(true);try { const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});setPreview(parseFacultyRows(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:null}),importYear)); } catch(e){setError(e.message);}finally{setBusy(false);} };
  const confirm = async () => {setBusy(true);setError('');try{const result=await request('/import',{rows:preview.rows});setNotice(`${result.count} results saved. Existing matching results were updated.`);setPreview(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}};
  const template = () => { const headers=['FACULTY NAME','EMAIL','PROJECT','SUBJECT','TEST NAME','TEST DATE','ATTEMPTED','CORRECT','MARKS','QUALIFICATION','STATUS','MAX MARKS','TOTAL QUESTIONS']; const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([headers]),'Faculty Results');XLSX.writeFile(wb,'Faculty-Test-Upload-Template.xlsx'); };
  return <div style={{display:'grid',gap:20}}>
    <section className="card"><h2>Faculty Test Analysis</h2><p>Faculty results are separate from student tests. Filter by year, test and subject for comparable rankings.</p>
      {isAdmin && <div style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><label>Import academic year <input className="input" value={importYear} onChange={e=>{setImportYear(e.target.value);setPreview(null);}} disabled={busy}/></label><label className="btn btn-primary">Upload Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={upload} disabled={busy || !importYear.trim()} style={{display:'none'}}/></label><button className="btn btn-ghost" onClick={template}>Download template</button></div>}
      {notice && <p role="status">{notice}</p>}{error && <p role="alert" style={{color:'#b91c1c'}}>{error} <button className="btn btn-ghost" onClick={load}>Retry loading</button></p>}
      {preview && <div><h3>Import preview — {preview.rows.length} results</h3><p>Confirming replaces matching year/email/test/subject results. Other tests remain unchanged. Blank future-test groups are skipped.</p>{preview.warnings.map((w,i)=><p key={i} style={{color:'#92400e'}}>{w}</p>)}<div style={{overflowX:'auto',maxHeight:300}}><table className="table"><thead><tr>{['Name','Email (required)','Test','Subject','Attempted','Correct','Marks','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i}><td>{r.name}</td><td><input aria-label={`Email for ${r.name}`} value={r.email} onChange={e=>{const email=e.target.value;setPreview(p=>({...p,rows:p.rows.map(x=>x.name===r.name?{...x,email}:x)}));}} /></td><td>{r.test}</td><td>{r.subject}</td><td>{show(r.attempted)}</td><td>{show(r.correct)}</td><td>{show(r.marks)}</td><td>{r.status}</td></tr>)}</tbody></table></div><button className="btn btn-primary" disabled={busy || preview.rows.some(r=>!r.email.includes('@'))} onClick={confirm}>{busy?'Saving…':'Confirm import'}</button> <button className="btn btn-ghost" disabled={busy} onClick={()=>setPreview(null)}>Cancel</button></div>}
    </section>
    {loading ? <p role="status">Loading faculty results…</p> : !rows.length ? <section className="card">No faculty test results uploaded yet.{isAdmin?' Upload the consolidated workbook above.':''}</section> : <>
      <section className="card" style={{display:'flex',gap:12,flexWrap:'wrap'}}>{[['Year',year,setYear,options('year')],['Test',test,setTest,options('test')],['Subject',subject,setSubject,options('subject')],['Centre/project',centre,setCentre,options('centres')]].map(([label,value,set,opts])=><label key={label}>{label}<select className="input select" value={value} onChange={e=>set(e.target.value)}><option value="ALL">All</option>{opts.map(v=><option key={v}>{v}</option>)}</select></label>)}</section>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}>{[['Appeared results',appeared.length],['Absent / on leave',filtered.filter(r=>['ABSENT','LEAVE','MEDICAL LEAVE'].includes(r.status)).length],['Average marks',canRank?show(mean('marks')):'Select year/test/subject'],['Average accuracy',mean('accuracy') === null?'—':`${show(mean('accuracy'))}%`],['Qualified results',filtered.filter(r=>r.qualification==='QUALIFIED').length]].map(([label,value])=><div className="card" key={label}><strong>{value}</strong><p>{label}</p></div>)}</div>
      <section className="card"><h3>Faculty marks comparison</h3>{canRank?<ResponsiveContainer width="100%" height={320}><BarChart data={appeared}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="marks" fill="#2563eb"/></BarChart></ResponsiveContainer>:<p>Select a year, test and subject to compare marks fairly.</p>}</section>
      <section className="card"><h3>Faculty progress across tests</h3><select className="input select" value={chosen} onChange={e=>setFaculty(e.target.value)}>{people.map(([email,name])=><option key={email} value={email}>{name}</option>)}</select><p>Accuracy is correct ÷ attempted. Marks percentage appears only when maximum marks are supplied. Without test dates, tests are ordered by name.</p><ResponsiveContainer width="100%" height={320}><LineChart data={history}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis yAxisId="marks"/><YAxis yAxisId="pct" orientation="right" domain={[0,100]}/><Tooltip/><Legend/><Line yAxisId="marks" dataKey="marks" name="Marks" stroke="#2563eb" connectNulls={false}/><Line yAxisId="pct" dataKey="accuracy" name="Accuracy %" stroke="#16a34a" connectNulls={false}/><Line yAxisId="pct" dataKey="percent" name="Marks %" stroke="#9333ea" connectNulls={false}/></LineChart></ResponsiveContainer></section>
      <section className="card" style={{overflowX:'auto'}}><h3>Test results — {filtered.length} records</h3><table className="table"><thead><tr>{['Rank','Faculty','Centre','Test','Subject','Attempted','Correct','Accuracy','Marks','Qualification','Status'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{ranking.map(r=><tr key={r._id}><td>{canRank && r.marks !== null ? 1+ranking.filter(o=>o.marks!==null && o.marks>r.marks).length:'—'}</td><td><button className="btn btn-ghost" onClick={()=>setFaculty(r.email)}>{r.name}</button></td><td>{r.centres.join(', ')}</td><td>{r.test}</td><td>{r.subject}</td><td>{show(r.attempted)}</td><td>{show(r.correct)}</td><td>{r.accuracy===null?'—':`${show(r.accuracy)}%`}</td><td>{show(r.marks)}</td><td>{r.qualification||'—'}</td><td>{r.status}</td></tr>)}</tbody></table>{!filtered.length&&<p>No results match these filters.</p>}</section>
    </>}
  </div>;
}
